from configparser import ConfigParser


LOCALHOST_ADDR = "127.0.0.1"

# конфиги айдишников для работы с бд

ITER_CATEGORY_NAME = 1
ITER_CATEGORY_ID = 0
ITER_CATEGORY_OZON_LINK = -1
ITER_CATEGORY_WB_LINK = -2
ITER_CATEGORY_ADMIN_CHAT_ID = 3
ITER_CATEGORY_CHANNEL_CHAT_ID = 4
ITER_CATEGORY_MULTI_CHANNEL_CHAT_ID = 5

ITER_PRODUCT_ID = 0
ITER_PRODUCT_TITLE = 1
ITER_PRODUCT_PRICE = 2
ITER_PRODUCT_PRICE_DISCOUNT = 3
ITER_PRODUCT_VENDOR_CODE = 4
ITER_PRODUCT_LINK = 5
ITER_PRODUCT_IMAGE_LINK = 6
ITER_PRODUCT_CREATED_AT = 7
ITER_PRODUCT_CATEGORY_ID = 8

TABLE_PRODUCTS = "products"
TABLE_SENT_TO_ADMIN = "sent_to_admin"
TABLE_CATEGORIES = "categories"

config = ConfigParser()
config.read("./conf.ini")

TOKEN = config["BOT"]["TOKEN"]
SUPER_ADMIN_CHAT_ID = int(config["BOT"]["SUPER_ADMIN_CHAT_ID"])
WEBHOOK_PATH = config["BOT"]["WEBHOOK_PATH"]
WEBHOOK_SECRET = config["BOT"]["WEBHOOK_SECRET"]
WEB_SERVER_PORT = int(config["BOT"]["WEB_SERVER_PORT"])
WEB_SERVER_HOST = config["BOT"]["WEB_SERVER_HOST"]

BASE_WEBHOOK_URL = config["SERVER"]["BASE_WEBHOOK_URL"]
ADMIN_WEBHOOK_PATH = config["SERVER"]["WEBHOOK_PATH"]

DB_HOST = config["DATABASE"]["HOST"]
DB_PORT = config["DATABASE"]["PORT"]
DB_USERNAME = config["DATABASE"]["USERNAME"]
DB_PASSWORD = config["DATABASE"]["PASSWORD"]
DB_DATABASE = config["DATABASE"]["DATABASE"]

DB_PRODUCTS_TABLE = config["DATABASE"]["PRODUCTS_TABLE"]
DB_SENT_TO_ADMIN_TABLE = config["DATABASE"]["SENT_TO_ADMIN_TABLE"]
DB_CATEGORIES_TABLE = config["DATABASE"]["CATEGORIES_TABLE"]

